### PR TITLE
Allow optional plugin prefix, adds support for multi instance monitoring 

### PR DESCRIPTION
**Pull request by pyh**
Now it's possible to add a prefix to the symbolic link eg:

userdata_memcached_commands
filedetails_memcached_commands
.. etc

You can then specify port/host for each instance in plugin-conf.d

### CODE REVIEW

**Comment by mhwest13** [comment]
Sorry man, I can't really accept this code...

It doesn't really add support for multi instance monitoring, because its still using / leveraging the same environment variables. All I can see this really does is add a title prefix to the graph. If the prefix was determined before the environment vars were instantiated, and then leveraged for selecting the vars, then I could see where its possible to setup multi instance monitoring, but I fail to see that code in this pull request...

Sorry for the late response, I haven't given this plugin very much attention in some time...

**Comment by mhwest13** [comment]
Actually, scratch that... It dawns on me now what you mean by the plugin-conf.d setup stuff and how that would come into play. Sometimes the simplest things aren't so obvious... Let me do some testing on the patch and I'll get it merged in, and possibly clean up memcached_ to be a bit more 1.2/1.4 cross compatible.

**Comment by laudaksg** [comment]
Makes a lot of sense to adjust the plugin to monitor multiple memcached server instances

**Comment by saily** [comment]
hi, any news on that? Still something missing? i'll offer some help if needed...

**Comment by mhwest13** [comment]
Sorry, I've been busy with a few personal things... I'll work on this sometime this week.

Cheers

**Comment by mhwest13** [comment]
OK guys, if you can do me a favor and try the plugins out that are in my dev-branch... The prefixing works in exactly the same way, only its been scrubbed a little more, and the regex matches are the same. I've done some base line testing on my dev box, and the stats / information looks correct.

If someone can at least do some spot checking for me before I push it into master, I would greatly appreciate it.

Cheers,

https://github.com/mhwest13/Memcached-Munin-Plugin/tree/dev-branch

**Comment by laudaksg** [comment]
Works like a charm :)  
Though the documentation should be updated as well (examples, description)

**Comment by mhwest13** [comment]
Ok gang, code is committed / pushed up to master, I've also updated the README to reflect some information about the prefixing... 

Going to close this ticket out...

Cheers,

Dev to Master Merge Located Here: a2d890d25f784166646b20157e893a1b70528eb2

**Pull request closed without merging**
